apiVersion: apps/v1
kind: Deployment
metadata:
  name: odatafiori 
  labels:
    app: odatafiori 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odatafiori 
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: odatafiori  
    spec:     # pod spec                  
      containers: 
      - image: mizmauzdocker/odatafiori:0.0.1 # image we pushed
        name: odatafiori  
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9005
---
apiVersion: v1
kind: Service
metadata:
  name: odatafiori 
  labels:
    app: odatafiori
spec:
  ports:
  - name: http
    port: 9005
    targetPort: 9005
  selector:
    app: odatafiori 